### ISSUE TITLE
Contao 4 BE double fields

### ISSUE THREAD

**Issue by garyee** [terminal42/contao-newslanguage#10]
Hi,

so I installed the extension in Contao 4 and I got ... kind of a problem, nothing serious but still.
All the fields are inserted two times.
I just droped the extension in /system/modules/.

![error_screen](https://user-images.githubusercontent.com/5537949/29618156-79cbc3aa-8817-11e7-8f6a-75f44f94209f.png)

**Comment by aschempp** [comment]
This extension is not necessary with Changelanguage 3
