### ISSUE TITLE
auto_item problem.

### ISSUE THREAD

**Issue by stefanheimes** [terminal42/contao-newslanguage#4]
Hi, i saw there is a PR for this problem, but i think it is to heavy for this "small" problem. So let's start. 

First, why is the current handling of the auto_item such a problem ? 
I think it is wrong to rewrite the auto_item to item. I know the news module from contao do it on the same way. But there is one problem. The module only do this when it is loaded. Your extension make this all the time. This is the main problem. 

How can we fix it ?
I found a realy simple idea, how it should work. 
See https://github.com/terminal42/contao-newslanguage/blob/master/NewsLanguage.php#L46

Change this code to 
```php 
		// Set the item from the auto_item parameter
		if ($GLOBALS['TL_CONFIG']['useAutoItem'] && isset($_GET['auto_item']))
		{
			$strItem = $this->Input->get('auto_item');
		}
		else
		{
			$strItem = $this->Input->get('items');
		}		
```
If you find a news entry you can rewrite the auto_item to item, if you can not find a news entry just ignore it, because we have not the news context we needed.

**Comment by qzminski** [comment]
14a9a27b23e1bc0ebe284a7faba9c92cb8252c0b should solve this problem.
