### ISSUE TITLE
Contao 4 BE CSS Problem

### ISSUE THREAD

**Issue by garyee** [terminal42/contao-newslanguage#9]
Hello

there is a little problem with the extentsion under Contao 4.
The install was no problem. But when I want to set the language for the news archive I am not able to access the field because the headline of the widget that comes after blocks it.

![error_screen](https://user-images.githubusercontent.com/5537949/29617680-f03e75ac-8815-11e7-80d9-2da50e8f11a8.png)

**Comment by aschempp** [comment]
see #10
